spring:
  h2:
    console:
      enabled: true
  datasource:
    password: password
    url: jdbc:h2:mem:epiapp
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  error:
    include-stacktrace: never