spring:
  h2:
    console:
      enabled: true
  datasource:
    password: password
    url: jdbc:h2:mem:epiapp
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  error:
    include-stacktrace: never
  port: 9000

security:
  jwt:
    # use 32+ chars
    secret: "a9F!2kLmP0sQzXyR7uVw#tBnE3hJ6dKc"
    expiration-seconds: 3600
